name: 'pheno_environment_fish'

metadata:
  description: 'Mapping file from ZFIN Environment to ZECO ID'

reader:
  format: 'csv'
  files:
    - '../data/pheno_environment_fish.txt'
  delimiter: '\t'
  header_mode: 'none'
  columns:
    - 'Environment ID'
    - 'ZECO Term Name'
    - 'ZECO Term ID (ZECO:ID)'
    - 'Chebi Term Name'
    - 'Chebi Term ID (Chebi:ID)'
    - 'ZFA Term Name'
    - 'ZFA Term ID (ZFA:ID)'
    - 'Affected Structure Subterm Name'
    - 'Affected Structure Subterm ID (GO-CC:ID)'
    - 'NCBI Taxon Name'
    - 'NCBI Taxon ID (NCBI Taxon:ID)'

transform:
  key: 'Environment ID'
  values:
    - 'ZECO Term ID (ZECO:ID)'
